HomePage/urls.py
from django.urls import path
from . import views
app_name="HomePageUrl"
urlpatterns = [
    path("HomePage",views.home_page,name="HomePage")
    
]

Ib7Main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from UserManageMent.views import login_page
from Shop.views import home_page
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/login', login_page),
    path('', home_page),
    path("InstallMent/",include("InstallMent.urls")),
    path("UserManageMent/",include("UserManageMent.urls")),
    path("Dashbord/",include("HomePage.urls")),
    path("ShopManageMent/",include("ShopManageMent.urls")),
    path("Networker/",include("NetworkerPanel.urls")),
    path("Market/",include("Shop.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ShopManageMent/urls.py
from django.urls import path
from . import views
app_name= "ShopManageMentUrl"
urlpatterns = [
    path("ProductList",views.product_list_page,name="ProductList"),
    path("EditProduct/<int:product_id>",views.edit_product_page,name="EditProduct"),
    path("CreateProduct",views.create_product_page,name="CreateProduct"),
    path("AddMainFileProduct",views.add_main_file_product,name="AddMainFileProduct"),
    path("DeleteMainFileProduct",views.delete_main_image_product,name="DeleteMainFileProduct"),
    path("GaleryImageProduct",views.GaleryImageProduct.as_view(),name="GaleryImageProduct"),
    path("ProductManageMent",views.ProductManageMent.as_view(),name="ProductManageMent"),
    path("ProductManageMent/<int:product_id>",views.ProductManageMent.as_view(),name="ProductManageMent"),

    path("ChangeMainImageRro/<int:product_id>",views.chagne_main_image_product,name="ChangeMainImageRro"),
    path("DeleteMainImagePro/<int:product_id>",views.delete_main_image_pro,name="DeleteMainImagePro"),
    path("add_galery_image_topro/<int:product_id>",views.add_galery_image_topro,name="add_galery_image_topro"),
    path("delete_galery_image",views.delete_galery_image,name="delete_galery_image"),
    
    
    
    path("delete_main_image/<int:product_id>",views.delete_main_image,name="delete_main_image"),
    path("delete_g_image/<int:g_id>",views.delete_g_image,name="delete_g_image"),

    #CatehoryThree Begin 

    path("CategoryThree",views.category_three_page,name="CategoryThree"),
    path("CategoryThreeManager",views.CategoryThreeManager.as_view(),name="CategoryThreeManager"),
    path("CategoryThreeManager/<int:cat_id>",views.CategoryThreeManager.as_view(),name="CategoryThreeManager"),
    #CatehoryThree end

    #CatehoryTwo begin
    path("CategoryTwo",views.category_two_page,name="CategoryTwo"),
    path("CategoryTwoManager",views.CategoryTwoManager.as_view(),name="CategoryTwoManager"),
    path("CategoryTwoManager/<int:cat_id>",views.CategoryTwoManager.as_view(),name="CategoryTwoManager"),
    #CatehoryTwo end
    #Catehoryone begin

    path("CategoryOne",views.category_one_page,name="CategoryOne"),
    path("CategoryOneManager",views.CategoryOneManager.as_view(),name="CategoryOneManager"),
    path("CategoryOneManager/<int:cat_id>",views.CategoryOneManager.as_view(),name="CategoryOneManager"),

    # Category One ENd

    #ColorManager begin
    
    path("ColorList",views.color_list_page,name="ColorList"),
    path("ColorManager",views.ColorManager.as_view(),name="ColorManager"),
    path("ColorManager/<int:color_id>",views.ColorManager.as_view(),name="ColorManager"),
    #ColorManager end

    #SizeManager begin
    path("SizeList",views.size_list_page,name="SizeList"),
    path("SizeManager",views.SizeManager.as_view(),name="SizeManager"),
    path("SizeManager/<int:size_id>",views.SizeManager.as_view(),name="SizeManager"),

    #SizeManager end
    
    #Inventory Manager Begin
    path("InventoryList",views.inventorylist,name="InventoryList"),
    path("CreateOrEditInv/<int:product_id>",views.create_or_edit_inv_page,name="CreateOrEditInv"),
    
    path("InventoryManager",views.InventoryManager.as_view(),name="InventoryManager"),
    path("InventoryManager/<int:product_id>",views.InventoryManager.as_view(),name="InventoryManager"),
    path("error_text",views.error_text,name="error_text"),
    #Inventory Manager End

    #property and specifications
    path("PropertyManager/<int:property_id>",views.PropertyManager.as_view(),name="PropertyManager"),
    path("SpeciFicationManager/<int:sep_id>",views.SpeciFicationManager.as_view(),name="SpeciFicationManager"),
    #property and specifications
    path("ShowFilterManager/<int:show_id>",views.ShowFilterManager.as_view(),name="ShowFilterManager"),
    path("ShowFilterManager",views.ShowFilterManager.as_view(),name="ShowFilterManager"),
    path("ProductFilter",views.show_filter_page,name="show_filter_page"),
    path("SliderImage",views.slider_image_page,name="SliderImage"),
    path("SliderImageManager",views.SliderImageManager.as_view(),name="SliderImageManager"),
    path("SliderImageManager/<int:image_id>",views.SliderImageManager.as_view(),name="SliderImageManager"),
    path("AddSliderImageSession",views.AddSliderImageSession.as_view(),name="AddSliderImageSession"),
    path("ReturnTerms",views.return_terms_page,name="ReturnTerms"),
    path("HowToBuy",views.how_to_buy_page,name="HowToBuy"),
    path("TermsAndConditions",views.terms_and_c_page,name="TermsAndConditions"),
    path("WhyUs",views.why_us_page,name="WhyUs"),
    path("AbutUs",views.abut_us_page,name="AbutUs"),
    path("ManyQuestionManagr",views.ManyQuestionManagr.as_view(),name="ManyQuestionManagr"),
    path("ManyQuestionManagr/<int:quest_id>",views.ManyQuestionManagr.as_view(),name="ManyQuestionManagr"),
    path("QuestionManager/<int:question_id>",views.QuestionManager.as_view(),name="QuestionManager"),
    path("QuestionManager",views.QuestionManager.as_view(),name="QuestionManager"),
    path("ManyQuestion",views.many_question_page,name="ManyQuestion"),


]

urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from UserManageMent.views import login_page
from Shop.views import home_page
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/login', login_page),
    path('', home_page),
    path("InstallMent/",include("InstallMent.urls")),
    path("UserManageMent/",include("UserManageMent.urls")),
    path("Dashbord/",include("HomePage.urls")),
    path("ShopManageMent/",include("ShopManageMent.urls")),
    path("Networker/",include("NetworkerPanel.urls")),
    path("Market/",include("Shop.urls")),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ShopManageMent/views.py
from django.shortcuts import render,redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from .models import *
import json
from django.core.files.storage import FileSystemStorage
from pathlib import Path
import os
from .serializers import ProductSerializer
from .forms import *
from django.http import JsonResponse
# Create your views here.
def product_list_page(request):
    return render(request, 'ShopManageMent/ProductManageMent/ProductList.html', )

def create_product_page(request):
    categorys =CategoryOne.objects.all()
    showfilters =ShowFilter.objects.all()
    return render(request, 'ShopManageMent/ProductManageMent/CreateProduct.html',{"categorys":categorys,"showfilters":showfilters})

class ProductManageMent(APIView):
    def get(self,request):
        product = Product.objects.all()

        json_data = ProductSerializer(product,many=True).data
        return Response(status=status.HTTP_200_OK,data={"data":json_data})
    def post(self,request):
        
        data= request.data
   
        category= data.getlist('category')
        show_filters= data.getlist('show_filters')
        title= data['title']
        price= data['price']
        discription= data['discription']
        pr_list =data.getlist('pr_list')
        sp_list = data.getlist('sp_list')

        new_product=Product(
            title=title,
            price=price,
            discription=discription
        )
        
        try:
            image_path=request.session['image_path']
            file_name = os.path.basename(image_path)
          

            new_product.main_image.save(file_name,open(image_path,'rb'))
            path = Path(image_path)
            if path.exists():
                    path.unlink()
            request.session['image_path']=None
            
        except:
            pass
        new_product.save()
        try:
        
            image_paths=request.session.get('galery_image_product_ses')
            image_objs=[]
            for item in image_paths:
                image_model =Image()
                image_model.image_file.save(item['filename'],open(item['path'],'rb'))
                image_model.save()
                new_product.image.add(image_model)
                image_objs.append(image_model)

                path = Path(item['path'])
                if path.exists():
                    path.unlink()
            request.session['galery_image_product_ses']=[]
        except:
            pass
          

            
        
        code= new_product.id + 1000
        new_product.product_code=code
        new_product.save()
        for sp in sp_list:
            for item in json.loads(sp):
              
                new_specification =SpeciFication(
                    title=item['title'],
                    dis=item['dis']
                )
                new_specification.save()
                new_product.specification.add(new_specification)
        for pr in pr_list:
            for item in json.loads(pr):
                new_property = Propery(
                    title=item['title'],
                    dis=item['dis']
                )
                new_property.save()
                new_product.property.add(new_property)
        for cat in category:
            category_obj = CategoryOne.objects.get(id=cat)
            new_product.category.add(category_obj)
        for show in show_filters:
            showfilter = ShowFilter.objects.get(id=show)
            new_product.show_filters.add(showfilter)
        return Response(status=status.HTTP_200_OK)
    
    def put(self,request,product_id):
        product_obj=Product.objects.get(id=product_id)
        data= request.data
     
        pr_list =data.getlist('pr_list')
        sp_list = data.getlist('sp_list')
        for sp in sp_list:
            for item in json.loads(sp):
              
                new_specification =SpeciFication(
                    title=item['title'],
                    dis=item['dis']
                )
                new_specification.save()
                product_obj.specification.add(new_specification)
        for pr in pr_list:
            for item in json.loads(pr):
                new_property = Propery(
                    title=item['title'],
                    dis=item['dis']
                )
                new_property.save()
                product_obj.property.add(new_property)
        categorys = data.getlist("category")
        show_filters = data.getlist("show_filters")
        title= data['title']
        price= data['price']
        discription= data['discription']
        product_obj.title=title
        product_obj.price=price
        product_obj.discription=discription
        product_obj.save()    
        for category in categorys:
            cat_obj = CategoryOne.objects.get(id=category)
            
            product_obj.category.add(cat_obj)
        for show_filter in show_filters:
            show_filter_obj = ShowFilter.objects.get(id=show_filter)
            
            product_obj.show_filters.add(show_filter_obj)
        return Response(status=status.HTTP_200_OK)

    def delete(self,request,product_id):
        product_obj = Product.objects.get(id=product_id)
        product_obj.delete()
        return Response(status=status.HTTP_200_OK)
def handle_uploaded_file(file):
    with open('session_images/main_images/' + file.name, 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)
@api_view(["POST"])
def add_main_file_product (request):
    # request.session['image_path']=None
    image_file=handle_uploaded_file(request.FILES.get("file"))
    print(image_file)
  
    # request.session['main_image_product']=image_file
    request.session['image_path'] = 'session_images/main_images/' + request.FILES['file'].name
    return Response(status=status.HTTP_200_OK)

@api_view(['GET'])
def delete_main_image_product(request):
    image_path=request.session['image_path']

    path = Path(image_path)
    if path.exists():
        path.unlink()

        


    return Response(status=status.HTTP_200_OK)
def handle_uploaded_file_galery_image(file):
    with open('session_images/galery_images/' + file.name, 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)
class GaleryImageProduct(APIView):
    def post(self,request):
        
            image_file = handle_uploaded_file_galery_image(request.FILES.get("file"))
            # request.session['galery_image_product_ses'] =None
            try:
                
                ses=request.session.get('galery_image_product_ses')
                main_list=[]
                for item in ses:
                    main_list.append(item)
                main_list.append({'filename':request.FILES.get("file").name,"path":'session_images/galery_images/' + request.FILES.get("file").name})
                request.session['galery_image_product_ses']=main_list
                # ses.append({'filename':request.FILES.get("file").name,"path":'session_images/galery_images/' + request.FILES.get("file").name})
            except:

                
                request.session['galery_image_product_ses']=[{'filename':request.FILES.get("file").name,"path":'session_images/galery_images/' + request.FILES.get("file").name}]

            
            return Response(status=status.HTTP_200_OK)
    def get(self,request):
       
        file_name = request.GET.get("filename")
        main_list=[]
        
        for item in request.session['galery_image_product_ses']:
            
            if item['filename'] == file_name:
               
                path = Path(item['path'])
                if path.exists():
                    path.unlink()
            else:
                main_list.append(item)
        
        request.session['galery_image_product_ses']=main_list
        
        return Response(status=status.HTTP_200_OK)
    



def edit_product_page(request,product_id):
    product_obj = Product.objects.get(id=product_id)
    categorys = CategoryOne.objects.all()
    showfilters = ShowFilter.objects.all()
    category_list = [
    {
        "id": category.id,
        "title": category.title,
        "check": any(cat_pro.id == category.id for cat_pro in product_obj.category.all())
    }
    for category in categorys
    ]

    show_filter_list = [
        {
            "id": showfilter.id,
            "title": showfilter.title,
            "check": any(show_filter.id == showfilter.id for show_filter in product_obj.show_filters.all())
        }
        for showfilter in showfilters
    ]

            
    return render(request,'ShopManageMent/ProductManageMent/EditProduct.html',{'product_obj':product_obj,"categorys":category_list,"show_filter_list":show_filter_list})

@api_view(['POST'])
def chagne_main_image_product(request,product_id):
    file = request.FILES.get("file")
    product_obj =Product.objects.get(id=product_id)
    product_obj.main_image=file
    product_obj.save()    
    return Response(status=status.HTTP_200_OK,data={"url":product_obj.main_image.url})


@api_view(['GET'])
def delete_main_image_pro(request,product_id):
   
    product_obj =Product.objects.get(id=product_id)
    product_obj.main_image.delete()
    product_obj.save()    
    return Response(status=status.HTTP_200_OK)

@api_view(['POST'])
def add_galery_image_topro(request, product_id):
    image = request.FILES.get("file")

    product_obj = Product.objects.get(id=product_id)
    new_image = Image(image_file=image)
    new_image.save()
    product_obj.image.add(new_image)
    try:
                
        ses=request.session.get('galery_image_edit_product_ses')
        main_list=[]
        for item in ses:
            main_list.append(item)
        main_list.append({'filename':request.FILES.get("file").name,"id":new_image.id})

ShopManageMent/templates/ShopManageMent/Categorys/CategoryOneList.html
{% extends 'Ib7Base.html' %}
{% block content %}
<input type="hidden" id="CategoryData" value="{% url 'ShopManageMentUrl:CategoryOneManager' %}">
<div class="container-xxl flex-grow-1 container-p-y">
    <!-- Layout Demo -->
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-style2 mb-0">
            <li class="breadcrumb-item">
                <a href="{% url 'HomePageUrl:HomePage' %}">خانه</a>
            </li>
            <li class="breadcrumb-item">
                <a href="javascript:void(0);">مدیریت محصولات</a>
            </li>
            <li class="breadcrumb-item">
                <a href="javascript:void(0);">دسته بندی ها</a>
            </li>
            <li class="breadcrumb-item">
                <a href="javascript:void(0);">لیست دسته بندی اول</a>
            </li>

        </ol>
    </nav>
    <br>
    <div class="card">  
        <div class="modal fade" id="CreateCatThreeModal" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title secondary-font" id="modalCenterTitle">ایجاد دسته بندی جدید</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{% url 'ShopManageMentUrl:CategoryOneManager' %}" id="CreateCatThreeForm">
                        <div class="modal-body">
                            <div class="row">
                                {% csrf_token %}
                                <div class="col mb-3">
                                    <label for="nameWithTitle" class="form-label">عنوان دسته بندی</label>
                                    <input type="text" name="title" id="nameWithTitle" class="form-control"
                                        placeholder="عنوان را وارد کنید" required>
                                </div>
                            </div>
                            <div class="col mb-3">
                                <label for="selectpickerSelectDeselect" class="form-label">انتخاب دسته بندی
                                    دوم</label>
                                <select id="selectpickerSelectDeselect" name="category_three"
                                    class="selectpicker w-100" data-style="btn-default" multiple
                                    data-actions-box="true">
                                    {% for category_two_obj in category_two_objs %}
                                    <option value="{{category_two_obj.id}}">{{category_two_obj.title}}</option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">
                                بستن
                            </button>
                            <button type="submit" class="btn btn-primary" id="CreateCatThreeBtn">ذخیره تغییرات</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="card-header ">
            <h5 style="float:right;">لیست دسته بندی اول</h5>
            <button type="button" class="btn rounded-pill btn-secondary" data-bs-toggle="modal"
                data-bs-target="#CreateCatThreeModal" style="float:left;">ایجاد مورد جدید <i
                    class='bx bx-user-plus bx-tada'></i></button>
        </div>

        <div class="card-datatable text-nowrap">
            <table class="dt-scrollableTable table table-bordered">
                <thead>
                    <tr>
                        <th>شناسه</th>
                        <th>عنوان</th>




                        <th>عمل</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    {% for category in categorys %}
    <div class="modal fade" id="EditCategoryThreeModal_{{category.id}}" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title secondary-font" id="modalCenterTitle">ایجاد تغییر در دسته بندی</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'ShopManageMentUrl:CategoryOneManager' category.id %}"
                    id="EditCatThreeForm_{{category.id}}">
                    <div class="modal-body">
                        <div class="row">
                            <div class="col mb-3">
                                <label for="nameWithTitle" class="form-label">عنوان دسته بندی</label>
                                <input type="text" name="title" id="nameWithTitle" class="form-control"
                                    placeholder="عنوان را وارد کنید" required value="{{category.title}}">
                            </div>


                        </div>
                        <div class="col mb-3">
                            <label for="selectpickerSelectDeselect" class="form-label">انتخاب دسته بندی
                                دوم</label>
                            <select id="selectpickerSelectDeselect" name="category_three"
                                class="selectpicker w-100" data-style="btn-default" multiple
                                data-actions-box="true">
                                {% for category_three_obj in category.cat_three_ids %}
                                {% if category_three_obj.selected == True %}
                                <option selected value="{{category_three_obj.id}}">{{category_three_obj.title}}</option>
                                {% else %} 
                                <option  value="{{category_three_obj.id}}">{{category_three_obj.title}}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                        </div>

                    </div>
                    {% csrf_token %}
                    <input type="hidden" id="cat_id" value="{{category.id}}">
                    <div class="modal-footer">
                        <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">
                            بستن
                        </button>
                        <button type="button" class="btn btn-primary" id="EditCatThreeBtn_{{category.id}}"
                            onclick="EditCategory({{category.id}})">ذخیره تغییرات</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
    <!--/ Layout Demo -->
</div>
{% endblock content %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/bootstrap-select/bootstrap-select.css' %}">
<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css' %}">
<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/datatables-bs5/datatables.bootstrap5.css' %}">
<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/datatables-select-bs5/select.bootstrap5.css' %}">
<link rel="stylesheet"
    href="{% static 'frest_temp/vendor/libs/datatables-checkboxes-jquery/datatables.checkboxes.css' %}">
<link rel="stylesheet"
    href="{% static 'frest_temp/vendor/libs/datatables-fixedcolumns-bs5/fixedcolumns.bootstrap5.css' %}">
<link rel="stylesheet"
    href="{% static 'frest_temp/vendor/libs/datatables-fixedheader-bs5/fixedheader.bootstrap5.css' %}">
<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/animate-css/animate.css' %}">

<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/select2/select2.css' %}">
<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/tagify/tagify.css' %}">
<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/bootstrap-select/bootstrap-select.css' %}">
<link rel="stylesheet" href="{% static 'frest_temp/vendor/libs/sweetalert2/sweetalert2.css' %}">
{% endblock css %}
{% block page_js %}
{% load static %}
<!-- begin page js -->
<script src="{% static 'frest_temp/ShopJs/ShopManageMent/CategoryManager/CategoryTwoList.js' %}"></script>
<!-- page js -->
<script src="{% static 'frest_temp/js/ui-modals.js' %}"></script>
<script src="{% static 'frest_temp/js/forms-selects.js' %}"></script>
<script src="{% static 'frest_temp/js/forms-tagify.js' %}"></script>
<script src="{% static 'frest_temp/js/forms-typeahead.js' %}"></script>

<script src="{% static 'frest_temp/vendor/libs/select2/select2.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/select2/i18n/fa.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/tagify/tagify.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/bootstrap-select/bootstrap-select.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/bootstrap-select/i18n/defaults-fa_IR.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/bloodhound/bloodhound.js' %}"></script>
<script src="{% static 'frest_temp/js/extended-ui-sweetalert2.js' %}"></script>
{% endblock page_js %}
{% block vendors %}
{% load static %}
<script src="{% static 'frest_temp/vendor/libs/bootstrap-select/bootstrap-select.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables/i18n/fa.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables-bs5/datatables-bootstrap5.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables-responsive/datatables.responsive.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables-fixedcolumns/datatables.fixedcolumns.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables-fixedheader-bs5/fixedheader.bootstrap5.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables-select/datatables-select.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables-select-bs5/select.bootstrap5.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/datatables-checkboxes-jquery/datatables.checkboxes.js' %}"></script>
<script src="{% static 'frest_temp/vendor/libs/sweetalert2/sweetalert2.js' %}"></script>
{% endblock vendors %}